
const translations = {
    en: {
    home: "HOME",
    services: "SERVICES",
    projects: "PROJECTS",
    products: "PRODUCTS",
    blogs: "BLOGS",
    clients: "CLIENTS",
    about:"ABOUT US",
    contact: "CONTACT US",
    english: "English",
    arabic: "Arabic",
    obsessed:"We Are Obsessed With",
    technology:"Technology And Latest Updates",
    startProject:"Start Project" ,
    lorem: "Lorem Ipsum",
    dummyText:"is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,Lorem Ipsum has been the industry's",
    deliver:"We Deliver",
    software:"the Software You Need",
    welcome:"Welcome",
    discover:"Discover Our Company",
    bringing:"Bringing New IT Business solutions and ideas",
    simply:"Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry’s standard dummy text.",
    fromFunction:"From does follow function, which is why our software engineers are heavily involved in the project long. Both our design and development process follow the agile model.",
    pasionate:"We are pasionate",
    honest:"Honest Dependable",
    improving:"Always Improving",
    whatDo:"What I do?",
    expertise:"Here are some of my expertise",
    strategy:"Content Strategy",
    morbi:"Morbi vitae tristique sem, ut dignissim libero",
    vitae:"Morbi vitae tristique sem, ut dignissim libero",
    media:"Media Marketing",
    far:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. ",
    construction:"Construction Management",
    away:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts",
    finished:"Project Finished",   
    experience:"Your Experience", 
    happy:"Happy Clients",
    recognition:"Recognition",
    product:"Product",
    our:"Our Product",
    100:"100",
    49:"49",
    latest:"Our Latest Project",
    date:"April 14, 2018",
    colorful:"Colorful Small Cards",
    branding:"Branding",
    tell:"Tell us your plans, your goals, your deadlines, and your budget; we want to know it all. In this step, we explore our compatibility by listening quietly as we get to know you and your work.",
    storage:"Bucket Storage Device",
    corporate:"Corporate",
    plans:"Tell us your plans, your goals, your deadlines, and your budget; we want to know it all. in this step, we explore our compatibility by listening quietly as we get to know you and your work.",
    showCase:"Showcase",
    fromDoes:"From does follow function, which is why our software engineers are heavily involved in the project long. Both our design and development process follow the agile model.",
    getInTouch:"Get in Touch!",
    question:"For Any Question Please ,",
    contact:"Contact me!",
    
},
ar: {
    contact:"اتصل بي!",
    question:"لأي سؤال من فضلك ،",
    getInTouch:"ابقى على تواصل!",
    fromDoes:"من وظيفة المتابعة ، وهذا هو السبب في أن مهندسي البرمجيات لدينا يشاركون بشكل كبير في المشروع لفترة طويلة. تتبع كل من عملية التصميم والتطوير لدينا النموذج الرشيق.",
    showCase:"عرض",
    plans:"أخبرنا بخططك وأهدافك والمواعيد النهائية وميزانيتك ؛ نريد أن نعرف كل شيء. في هذه الخطوة ، نستكشف توافقنا من خلال الاستماع بهدوء بينما نتعرف عليك وعلى عملك.",
    corporate:"شركة كبرى",


    
    storage:"",
    tell:"أخبرنا بخططك وأهدافك والمواعيد النهائية وميزانيتك ؛ نريد أن نعرف كل شيء. في هذه الخطوة ، نستكشف توافقنا من خلال الاستماع بهدوء بينما نتعرف عليك وعلى عملك.",
    branding:"العلامة التجارية",
    colorful:"بطاقات صغيرة ملونة",
    date:"١٤ ابريل ٢٠١٨",
    latest:"أحدث مشروع لدينا",
    49:"٤٩",
    100:"١٠٠",
    our:"منتجنا",
    product:"منتج",
    recognition:"تعرُّف",
    happy:"عملاء سعداء",
    experience:"خبرتك",
    finished:"انتهى المشروع",



    away:"نلتزم بتسليم المشاريع والوفاء بالموعد النهائي ونحافظ على الجودة",
    construction:"إدارة الإنشاءات",
    far:"بعيدًا ، خلف كلمة الجبال ، بعيدًا عن بلاد فوكاليا وكونسونانتيا ، تعيش النصوص العمياء.",
    media:"التسويق الإعلامي",
    vitae:"نحن نبذل قصارى جهدنا لفهم احتياجاتك ، ونضيفك إلى العملية باستخدام الأفضل",
    morbi:"نستخدم أحدث الأدوات لإدارة كل مهمة لتحقيق أفضل أداء",
    strategy:"استراتيجية المحتوى",
    expertise:"هنا بعض من خبرتي",
    whatDo:"ماذا أفعل؟",


    
    improving:"دائما تتحسن",
    honest:"صادق يمكن ",
    pasionate:"نحن متحمسون",
    fromFunction:"من وظيفة المتابعة ، وهذا هو السبب في أن مهندسي البرمجيات لدينا يشاركون بشكل كبير في المشروع لفترة طويلة. تتبع كل من عملية التصميم والتطوير لدينا النموذج الرشيق.",
    simply:"لوريم إيبسوم هو ببساطة نص شكلي للطباعة وكان التنضيد هو النص الوهمي القياسي في الصناعة.",
    bringing:"تقديم حلول وأفكار جديدة لأعمال تكنولوجيا المعلومات",
    discover:"اكتشف شركتنا",
    welcome:"أهلا وسهلا",
    software:"البرنامج الذي تحتاجه",
    deliver:"نحن نسلم",
    dummyText:"نحن نقدم مجموعة كاملة من خدمات تكنولوجيا المعلومات من تصميم البرمجيات وتطويرها وتنفيذها واختبارها ، لدعمها وصيانتها    ",
    home: "الصفحة الرئيسية",
    services:"الخدمات",
    projects: "المشاريع",
    products: "الأخبار",
    blogs:  "الأنظمه",
    clients: "العملاء",
    contact: "تواصل معنا",
    about: "من نحن",
    english: "الانجليزية",
    arabic: "العربية",
    obsessed:"نحن مهووسون",
    technology:"التكنولوجيا وآخر التحديثات",
    startProject: "ابدأ المشروع",
    lorem:"لوريم إيبسوم" ,



},
};
